interface: lo  # network interface to listen for packets
time_window: 5  # Time window in seconds to consider connection attempts
port_threshold: 5  # Minimum number of different ports indicating a possible scan
fragmentation_limit: 5  # Limit of packet fragments before considering evasion
